// assistant-web-client/src/pages/LoginCallback.vue
<script setup>
import { onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUserStore } from '../store/userStore'
import baseApi from '../utils/baseApi'

const route = useRoute()
const router = useRouter()
const userStore = useUserStore()

onMounted(async () => {
  try {
    const tempToken = route.query.temp_token
    if (!tempToken) {
      router.push('/')
      return
    }

    const response = await baseApi.get('/auth/validate-token', {
      params: { temp_token: tempToken }
    })

    if (response.status !== 200) {
      throw new Error('Failed to complete authentication')
    }

    await userStore.checkAuth()
    router.push('/workspace')

  } catch (error) {
    console.error('Authentication error:', error)
    router.push('/')
  }
})
</script>

// assistant-web-client-v2/src/pages/LoginCallback.tsx
import { useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import apiClient from '../services/apiClient';

const LoginCallback = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { login } = useAuth();

  useEffect(() => {
    const tempToken = searchParams.get('temp_token');

    const validateToken = async () => {
      if (!tempToken) {
        navigate('/');
        return;
      }

      try {
		    const validateResponse = await apiClient.get(`/auth/validate-token?temp_token=${tempToken}`);

        if (validateResponse.status != 200) {
          throw new Error('Token validation failed');
        }

        const { data: user } = await apiClient.get('/auth/me');

        login(user);
        navigate('/workspace');
      } catch (error) {
        console.error('Login callback error:', error);
        navigate('/');
      }
    };

    validateToken();
  }, [searchParams, login, navigate]);

  return <p>Logging in...</p>;
};

export default LoginCallback;
